x=1
if x>0:
    print("These are two comments")
    print("Statement1")
print("Statement2")
#You can write two statements on single line
print("Statement1");print("Statement2")
x=1
if x>0:
 print("This statement has not indentation")
x=1
if x>0:
 print("This statement has single space indentation")
 x=1
if x>0:
    print("This statement has single tab indentation")
    x=1
if x>0:
    print("This statement has single space+tab indentation")
    a=1234
print(type(a))
b=(-5678)
print(type(b))
c=0
print(type(c))
g=1.03
print(type(g))
h=-11.23
print(type(h))
i=.23
print(type(i))
j=2.12e-10
print(type(j))
k=5E220
print(type(k))
x=complex(1,2)
print(type(x))
print(x)
z=1+2j
print(type(z))
z=1+2J
print(type(z))
x=True
print(type(x))
y=False
print(type(y))
str1 = "String" #start and end with double quotes
print(str1)
str2 = 'String' #start and end with single quotes
print(str2)
#str3 = "String' #ERROR: start with double quotes and end with single quotes
#str3 = 'String" #ERROR: start with single quotes and end with double quotes
str4 =  "Day's" #single quote inside double quotes
print(str4)
str5 = 'Day"s' #double quote inside single quotes
print(str5)
print("This is a backslash (\\) mark.")
print("This is tab \t key.")
print("This is a new line. \nNew line.")
print("These are \'single quotes \'")
print("These are \" double quotes\"")
string1 = "PYTHON TUTORIAL"
print (string1[0])
print (string1[-15]) #start with backwards last character has -1 index
print (string1[14])
print (string1[-1])
print (string1[4])
print (string1[-11])
print (string1[14])
my_list1 = [1, 2, 3, 4, 5]
print(my_list1)
my_list2 = ["red", "blue", "black", "white"]
print(my_list2)
my_list3 =['red' , 12 , 12.234]
print(my_list3)
my_list = []
print(my_list)
color_list = ["RED", "BLUE", "GREEN", "BLACK"]
print(color_list[0])
print(color_list[0],color_list[3])
print(color_list[-1])
print(color_list[2])
color_list = ["RED", "BLUE", "GREEN", "BLACK"]
# list slicing:
#     ListName{startIIndex:endIndex} last index is not included in the output
print(color_list[0:2])
print(color_list[1:2])
print(color_list[1:-2])
print(color_list[:3])
print(color_list[:])
